# -*- coding: utf-8 -*-
"""MultiProcessingQueue.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZrMkD4QGKYVOcQyAoUDabqHDU8yyS_ci
"""

# How to use multiprocessing.Queue as a FIFO queue:

from multiprocessing import Queue

customQueue = Queue(maxsize= 3)
customQueue.put(1)
print(customQueue.get())

